apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    app: {{ .Values.appName }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes | join ", " }}
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: "/mnt/data/{{ .Values.appName }}"
