apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080 # Jenkins Web Interface
        - containerPort: 50000 # Jenkins Agent to Master communication
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: docker-socket
          mountPath: /var/run/docker.sock  # Mount Docker socket
        - name: helm-bin
          mountPath: /usr/local/bin/helm  # Mount Helm binary if needed
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock  # Use Docker from host
      - name: helm-bin
        hostPath:
          path: /usr/local/bin/helm  # Use Helm from host (ensure Helm is installed)
