appName: rabbitmq
namespace: default

podSpec:
  numReplicas: 1

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 8Gi