name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        chmod 600 kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy RabbitMQ
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm upgrade --install rabbitmq bitnami/rabbitmq -f helm-charts/rabbitmq/values.yaml

    - name: Deploy Consumer
      run: helm upgrade --install consumer ./helm-charts/consumer

    - name: Deploy Producer
      run: helm upgrade --install producer ./helm-charts/producer

    - name: Clean up
      run: rm kubeconfig