name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push consumer image
      uses: docker/build-push-action@v2
      with:
        context: ./consumer
        push: true
        tags: sahar567/consumer-image:latest

    - name: Build and push producer image
      uses: docker/build-push-action@v2
      with:
        context: ./producer
        push: true
        tags: sahar567/producer-image:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name : Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    
    - name: install kuberneters
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Add Helm Repo
      run: helm repo add stable https://charts.helm.sh/stable

    - name: Deploy RabbitMQ
      run: |
        helm install rabbitmq helm-charts/rabbitmq

    - name: Deploy Consumer
      run: |
        helm install consumer helm-charts/consumer
      
    - name: Deploy Producer
      run: |
        helm install producer helm-charts/producer