name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push consumer image
      uses: docker/build-push-action@v2
      with:
        context: ./consumer
        push: true
        tags: sahar567/consumer-image:latest

    - name: Build and push producer image
      uses: docker/build-push-action@v2
      with:
        context: ./producer
        push: true
        tags: sahar567/producer-image:latest